### PR TITLE
fix: keyedParameters use unique key

### PR DESCRIPTION
**Pull request by liangskyli**
## Changes
fix: #1798 
_What does this PR change? Link to any related issue(s)._

## How to Review

_How can a reviewer review your changes? What should be kept in mind for this review?_

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

**Review by drwpow — APPROVED** [review]
🎉🎉🎉 Looks great, thank you!

Great test too. We’ll need a `patch` changeset in order to release this though (see comment above)

**Comment by drwpow** [comment]
Ah I see—this is caused by the hoisted parameters test. It’s important **that test still passes without modification** but any implementation we can take that makes the test suite pass is fine by me.

**Comment by liangskyli** [comment]
> Ah I see—this is caused by the hoisted parameters behavior. It’s important **that test still passes without modification** but any implementation we can take that makes the test suite pass is fine by me.

fix it.

**Comment by liangskyli** [comment]
@drwpow :There are issues with different types of parameters with the same name. I hope this bug can be released as soon as possible. Thank you!

**Comment by drwpow** [comment]
@liangskyli This looks great, thanks for fixing the tests! We’ll need a `patch` changeset )[see comment](https://github.com/openapi-ts/openapi-typescript/pull/1849#issuecomment-2288740140)) to release though!

**Comment by liangskyli** [comment]
I have already create proud-pugs-clean.md file

**Pull request merged**
