### PR TITLE
Check `result` type before using `in` operator

### PR DESCRIPTION
**Pull request by simensol**
## Changes

Make sure `result` is an object before using the `in` operator. Fixes the following errors when generating a schema:

```bash
node_modules/openapi-typescript/dist/transform/schema-object.js:149
                if ("schema" in result) {
                             ^

TypeError: Cannot use 'in' operator to search for 'schema' in UUID
    at transformSchemaObjectCore (node_modules/openapi-typescript/dist/transform/schema-object.js:149:30)
    at transformSchemaObjectWithComposition (node_modules/openapi-typescript/dist/transform/schema-object.js:108:28)
    at transformSchemaObject (node_modules/openapi-typescript/dist/transform/schema-object.js:6:18)
    at transformParameterObject (node_modules/openapi-typescript/dist/transform/parameter-object.js:4:37)
    at transformParametersArray (node_modules/openapi-typescript/dist/transform/parameters-array.js:30:19)
    at transformOperationObject (node_modules/openapi-typescript/dist/transform/operation-object.js:9:18)
    at injectOperationObject (node_modules/openapi-typescript/dist/transform/operation-object.js:38:18)
    at transformPathItemObject (node_modules/openapi-typescript/dist/transform/path-item-object.js:37:13)
    at Object.transformPathsObject [as paths] (node_modules/openapi-typescript/dist/transform/paths-object.js:18:34)
    at transformSchema (node_modules/openapi-typescript/dist/transform/index.js:20:47)
```

```bash
node_modules/openapi-typescript/dist/transform/schema-object.js:298
                        if ("schema" in result) {
                                     ^

TypeError: Cannot use 'in' operator to search for 'schema' in UUID
    at transformSchemaObjectCore (node_modules/openapi-typescript/dist/transform/schema-object.js:298:38)
    at transformSchemaObjectWithComposition (node_modules/openapi-typescript/dist/transform/schema-object.js:108:28)
    at Object.transformSchemaObject [as schemas] (node_modules/openapi-typescript/dist/transform/schema-object.js:6:18)
    at Object.transformComponentsObject [as components] (node_modules/openapi-typescript/dist/transform/components-object.js:25:48)
    at transformSchema (node_modules/openapi-typescript/dist/transform/index.js:20:47)
    at openapiTS (node_modules/openapi-typescript/dist/index.js:65:20)
```

### CODE REVIEW

**Comment by drwpow** [comment]
Thanks @simensol! This fix looks good, but it needs 2 things to be approved:

1. Test added to guard against regressions
2. Changeset (`pnpm exec changeset` from root)

**Comment by simensol** [comment]
I really tried to create a test. But coming from Python, I don't really know the basics of writing TypeScript tests. I managed to run the existing test suite, but I didn't manage to write a test of my change. However, I have created the Changeset as requested.

**Comment by drwpow** [comment]
If you’re not able to provide a test, could you provide a schema you’re using, or implementation where this fails? Without a test it’s not clear what scenario leads to this error, since this doesn’t happen in the existing tests.

**Comment by simensol** [comment]
Sure! Here is a minimal schema that raises the error:

```yaml
openapi: 3.0.3
info:
    title: Test API
    version: 0.1.0
    description: Test
paths:
    /guardians/:
        get:
            operationId: guardians_list
            security:
                - cookieAuth: []
                - basicAuth: []
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Guardian"
components:
    schemas:
        Guardian:
            type: object
            properties:
                children:
                    type: array
                    items:
                        type: string
                        format: uuid
```

**Comment by drwpow** [comment]
Thanks! And I take it you’re using the Node.js API + `transform()` to turn it into a UUID? Because that functionality doesn’t exist natively without some modification.

Further, is it desirable that in those cases, the default transformer just stop executing if the node has been touched (which I think is what your PR changes, which is preferable to erring out but wanted to double-check)?

**Pull request merged**
