### PR TITLE
feat(openapi-react-query): Introduce createQuery

### LINKED ISSUE #1807: openapi-react-query: support for useQueries()
@drwpow @kerwanp Do you guys think that it's possible to add support for `useQueries()`? I'll work on that but need some directions and opinions.

### PR DESCRIPTION
**Pull request by zsugabubus**
## Changes

Fixes #1807. Instead of adding a dedicated `useQueries` function I would like propose a general query builder solution, this way not only `useQueries`, but all similar functions are covered for free.

~~Unfortunately, I could not resist and introduced two other (minor) changes on my way to the new feature. I'm happy to remove/split them. Please see changeset.~~

## How to Review

- Please check proposed API changes first.

## Checklist

- [x] Unit tests updated
- [x] `docs/` updated

### CODE REVIEW

**Comment by kerwanp** [comment]
Hi @zsugabubus! Thanks a lot for willing to contribute, there are really interesting ideas here!

As stated in the [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-react-query/CONTRIBUTING.md#opening-a-pull-request) we require new features are discussed first in an issue so you do no one waste time writing code that might not be accepted.

Regarding your Pull request, there are three related issues:
- https://github.com/openapi-ts/openapi-typescript/issues/1806
- https://github.com/openapi-ts/openapi-typescript/issues/1828
- https://github.com/openapi-ts/openapi-typescript/issues/1807

Aswell, it is always good to avoid mixing new features in the same PR (when possible):

## Pass down signal to fetch function this way `useQuery` can cancel queries.

This was definitely a requirement, great change! Could you open a new PR with the only this update, the related tests and a changeset. Once done, it should be ready to be merged.

## Add default `queryClient` parameter to `createClient`.

I guess that this feature can be usefull when we cant to use different QueryClient with the api than the default one provided to tanstack. I don't have any use case in mind but this might be useful. Same as the previous feature, feature, tests and changeset in a separated PR. I think it might be interesting to improve a bit the documentation to warn users that by passing the QueryClient here it will always override the one provided by the QueryClientProvider.
After that, ready to merge!

## Introduce `createQuery` that can be used as a building block to integrate with `useQueries`/`fetchQueries`/`prefetchQueries`… etc.

Regarding this feature, this is something under discussion here https://github.com/openapi-ts/openapi-typescript/issues/1806#issuecomment-2286518408 that should help/solve the following issues:
- https://github.com/openapi-ts/openapi-typescript/issues/1828
- https://github.com/openapi-ts/openapi-typescript/issues/1807
- https://github.com/openapi-ts/openapi-typescript/issues/1806
- https://github.com/openapi-ts/openapi-typescript/issues/1804

Let's first agree on the solution to adopt and we can the implement it.

Thanks again for your contribution and sorry for delaying this PR!

**Comment by zsugabubus** [comment]
Removed the other features and (seeing the other issues) I renamed the function to `queryOptions`. I never really liked `createQuery` (I attempted to shorten `createQueryOptions`) because what does it mean to "create a query"? Will it perform fetch… etc?

**Comment by kerwanp** [comment]
> Removed unrelated features and (seeing the other issues) I renamed the function to `queryOptions`. I never really liked `createQuery` (I attempted to shorten `createQueryOptions`) because what does it mean to "create a query"? Will it perform fetch… etc?

Hi @zsugabubus, I think this is ready to merge. We just need the documentation for the new `queryOptions` method, could you do it?

**Comment by zsugabubus** [comment]
@kerwanp Added docs but I have to say I'm not a good writer.

**Comment by kerwanp** [comment]
Hi @zsugabubus, thanks for the docs 👌 ! I merged https://github.com/openapi-ts/openapi-typescript/pull/1864 but that causes small conflicts. Could you fix them?

**Comment by zsugabubus** [comment]
@kerwanp Rebased.

**Pull request merged**
