### PR TITLE
Improve middleware type definition

### LINKED ISSUE #1916: Improvement suggestion for Middleware type definition
**Description**

The middleware throws the following error when neither `onRequest()` nor `onResponse()` is provided.

> "Middleware must be an object with one of onRequest() or onResponse()"
> https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/src/index.js#L223

Based on this, I think the type definition below could be improved by making it more explicit and better aligned with the intended behavior: https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/src/index.d.ts#L147

**Proposal**

It seems like the `Middleware` interface might be improved with the following modification:

```typescript
export type Middleware {
  onRequest?: ...;
  onResponse: ...;
} | {
  onRequest: ...;
  onResponse?: ...;
}
```

This modification ensures that either onRequest or onResponse is required, and this is reflected in the type, allowing the issue to be detected at compile time.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by yicrotkd**
## Changes

This PR updates the Middleware type definition to ensure that either `onRequest` or `onResponse` must be provided, as reflected in the error:

> "Middleware must be an object with one of onRequest() or onResponse()"

(see https://github.com/openapi-ts/openapi-typescript/issues/1916)

The new type definition introduces a union that enforces this behavior, allowing the absence of both methods to be detected at compile time.

## How to Review

Please review the changes to ensure that the new type definition accurately reflects the expected behavior. The key point is that a type error should occur only if neither onRequest nor onResponse is provided. Additionally, please check that existing middleware implementations are unaffected by this change.

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

Closes #1916

### CODE REVIEW

**Comment by drwpow** [comment]
Great fix, and great test! Happy to merge this, but first we need a `patch` changeset to release this (see comment for instructions)

**Comment by yicrotkd** [comment]
Thank you! I've added a `patch` changeset.

**Review by drwpow — APPROVED** [review]
Thank you!

**Comment by topaxi** [comment]
With this change, it is no longer possible to have classes implement the `Middleware` interface.

```typescript
class MyMiddleware implements Middleware { ... }
```

Results in:

```
error TS2422: A class can only implement an object type or intersection of object types with statically known members.
```

**Pull request merged**
