### PR TITLE
Apply encodeURIComponent on path parameter value

### PR DESCRIPTION
**Pull request by swachter**
## Changes

Fixes https://github.com/drwpow/openapi-typescript/issues/1596

## How to Review

_How can a reviewer review your changes? What should be kept in mind for this review?_

## Checklist

- [ ] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

**Comment by drwpow** [comment]
Good addition, but could you add a test (preferably one that fails before this change)? Thanks!

**Comment by StefanWachter1507** [comment]
I am sorry. I am unable to provide a test.

I have difficulties to work on the project. I installed `pnpm` and run `pnpm i`. Yet, the test fails.
```
> openapi-typescript-monorepo@0.0.0 test /home/stwachte/projects/eigene/openapi-typescript
> pnpm run -r --parallel --aggregate-output test

Scope: 8 of 9 workspace projects
packages/openapi-fetch test$ pnpm run "/^test:/"
packages/openapi-typescript test$ pnpm run "/^test:/"
packages/openapi-typescript-helpers test$ tsc --noEmit
packages/openapi-typescript test:  ERR_PNPM_NO_SCRIPT  Missing script: /^test:/
packages/openapi-typescript test: Failed
/home/stwachte/projects/eigene/openapi-typescript/packages/openapi-typescript:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  openapi-typescript@7.0.0-rc.0 test: `pnpm run "/^test:/"`
Exit status 1
 ELIFECYCLE  Test failed. See above for more details.
```

 I tried it both, running `pnpm test` in the root folder and in the `openapi-fetch` folder. In addition, IntelliJ-Ultimate does not understand the project structure properly.

**Comment by drwpow** [comment]
The package’s [CONTRIBUTING guide](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md#testing) has some basic instructions on test setup. You can also inspect `.github/workflows/ci.yml` to see the exact commands CI runs (which happens on a clean environment so it contains all the setup)

Also make sure you have pnpm 9 (current) and Node 22 (current) installed.

**Comment by StefanWachter1507** [comment]
I finally managed to run tests and found that the `params / paths / allows UTF-8 characters` test failed after my changes. IMHO that test should have failed because the question mark character in a path parameter should not be interpreted as the query string separator. I fixed that test to expect the path parameter to be url-encoded.

**Comment by drwpow** [comment]
Ah yes you’re right! Good catch—I agree that’s an improvement.

This PR still needs a test unique to your change, though! Preferably one that fails before your change.

**Comment by StefanWachter1507** [comment]
I added two more tests and changed the existing "allows UTF-8 characters" test slightly.

**Review by drwpow — APPROVED** [review]
Great work, thank you!

**Comment by drwpow** [comment]
> When will this be released? 

It’s being published right now 🙂. Thanks to changesets, the release process is automated

**Pull request merged**
